<?php
return [
    'tax_office' => [
        "Drugi Mazowiecki Urząd Skarbowy w Warszawie",
        "Drugi Śląski Urząd Skarbowy w Bielsku-Białej",
        "Drugi Urząd Skarbowy Kraków",
        "Drugi Urząd Skarbowy Łódź-Bałuty",
        "Drugi Urząd Skarbowy Łódź-Górna",
        "Drugi Urząd Skarbowy Warszawa-Śródmieście",
        "Drugi Urząd Skarbowy w Białymstoku",
        "Drugi Urząd Skarbowy w Bielsku-Białej",
        "Drugi Urząd Skarbowy w Bydgoszczy ",
        "Drugi Urząd Skarbowy w Częstochowie ",
        "Drugi Urząd Skarbowy w Gdańsku ",
        "Drugi Urząd Skarbowy w Gdyni ",
        "Drugi Urząd Skarbowy w Gliwicach ",
        "Drugi Urząd Skarbowy w Kaliszu ",
        "Drugi Urząd Skarbowy w Katowicach ",
        "Drugi Urząd Skarbowy w Kielcach ",
        "Drugi Urząd Skarbowy w Koszalinie ",
        "Drugi Urząd Skarbowy w Lublinie ",
        "Drugi Urząd Skarbowy w Opolu ",
        "Drugi Urząd Skarbowy w Radomiu ",
        "Drugi Urząd Skarbowy w Rzeszowie ",
        "Drugi Urząd Skarbowy w Szczecinie ",
        "Drugi Urząd Skarbowy w Tarnowie ",
        "Drugi Urząd Skarbowy w Toruniu ",
        "Drugi Urząd Skarbowy w Zielonej Górze ",
        "Drugi Wielkopolski Urząd Skarbowy w Kaliszu ",
        "Kujawsko-Pomorski Urząd Skarbowy w Bydgoszczy ",
        "Łódzki Urząd Skarbowy w Łodzi ",
        "Lubelski Urząd Skarbowy w Lublinie ",
        "Lubuski Urząd Skarbowy w Zielonej Górze ",
        "Małopolski Urząd Skarbowy w Krakowie ",
        "Opolski Urząd Skarbowy w Opolu ",
        "Pierwszy Mazowiecki Urząd Skarbowy w Warszawie ",
        "Pierwszy Śląski Urząd Skarbowy w Sosnowcu ",
        "Pierwszy Urząd Skarbowy Łódź-Bałuty ",
        "Pierwszy Urząd Skarbowy Łódź-Górna ",
        "Pierwszy Urząd Skarbowy Warszawa-Śródmieście ",
        "Pierwszy Urząd Skarbowy w Białymstoku ",
        "Pierwszy Urząd Skarbowy w Bielsku-Białej ",
        "Pierwszy Urząd Skarbowy w Bydgoszczy ",
        "Pierwszy Urząd Skarbowy w Częstochowie ",
        "Pierwszy Urząd Skarbowy we Wrocławiu ",
        "Pierwszy Urząd Skarbowy w Gdańsku ",
        "Pierwszy Urząd Skarbowy w Gdyni ",
        "Pierwszy Urząd Skarbowy w Gliwicach ",
        "Pierwszy Urząd Skarbowy w Kaliszu ",
        "Pierwszy Urząd Skarbowy w Katowicach ",
        "Pierwszy Urząd Skarbowy w Kielcach ",
        "Pierwszy Urząd Skarbowy w Koszalinie ",
        "Pierwszy Urząd Skarbowy w Krakowie ",
        "Pierwszy Urząd Skarbowy w Lublinie ",
        "Pierwszy Urząd Skarbowy w Opolu ",
        "Pierwszy Urząd Skarbowy w Poznaniu ",
        "Pierwszy Urząd Skarbowy w Radomiu ",
        "Pierwszy Urząd Skarbowy w Rzeszowie ",
        "Pierwszy Urząd Skarbowy w Szczecinie ",
        "Pierwszy Urząd Skarbowy w Tarnowie ",
        "Pierwszy Urząd Skarbowy w Toruniu ",
        "Pierwszy Urząd Skarbowy w Zielonej Górze ",
        "Pierwszy Wielkopolski Urząd Skarbowy w Poznaniu ",
        "Podkarpacki Urząd Skarbowy w Rzeszowie ",
        "Podlaski Urząd Skarbowy w Białymstoku ",
        "Pomorski Urząd Skarbowy w Gdańsku ",
        "Świętokrzyski Urząd Skarbowy w Kielcach ",
        "Trzeci Mazowiecki Urząd Skarbowy w Radomiu ",
        "Trzeci Urząd Skarbowy Warszawa-Śródmieście ",
        "Trzeci Urząd Skarbowy w Bydgoszczy ",
        "Trzeci Urząd Skarbowy w Gdańsku ",
        "Trzeci Urząd Skarbowy w Lublinie ",
        "Trzeci Urząd Skarbowy w Szczecinie ",
        "Urząd Skarbowy Kraków-Krowodrza ",
        "Urząd Skarbowy Kraków-Nowa Huta ",
        "Urząd Skarbowy Kraków-Podgórze ",
        "Urząd Skarbowy Kraków-Prądnik ",
        "Urząd Skarbowy Kraków-Śródmieście ",
        "Urząd Skarbowy Kraków-Stare Miasto ",
        "Urząd Skarbowy Łódź-Polesie ",
        "Urząd Skarbowy Łódź-Śródmieście ",
        "Urząd Skarbowy Łódź-Widzew ",
        "Urząd Skarbowy Poznań-Grunwald ",
        "Urząd Skarbowy Poznań-Jeżyce ",
        "Urząd Skarbowy Poznań-Nowe Miasto ",
        "Urząd Skarbowy Poznań-Wilda ",
        "Urząd Skarbowy Poznań-Winogrady ",
        "Urząd Skarbowy w Aleksandrowie Kujawskim ",
        "Urząd Skarbowy Warszawa-Bemowo ",
        "Urząd Skarbowy Warszawa-Bielany ",
        "Urząd Skarbowy Warszawa-Mokotów ",
        "Urząd Skarbowy Warszawa-Praga ",
        "Urząd Skarbowy Warszawa-Targówek ",
        "Urząd Skarbowy Warszawa-Ursynów ",
        "Urząd Skarbowy Warszawa-Wawer ",
        "Urząd Skarbowy Warszawa-Wola ",
        "Urząd Skarbowy w Augustowie ",
        "Urząd Skarbowy w Bartoszycach ",
        "Urząd Skarbowy w Będzinie ",
        "Urząd Skarbowy w Bełchatowie ",
        "Urząd Skarbowy w Białej Podlaskiej ",
        "Urząd Skarbowy w Białobrzegach ",
        "Urząd Skarbowy w Białogardzie ",
        "Urząd Skarbowy w Bielsku Podlaskim ",
        "Urząd Skarbowy w Biłgoraju ",
        "Urząd Skarbowy w Bochni ",
        "Urząd Skarbowy w Bolesławcu ",
        "Urząd Skarbowy w Braniewie ",
        "Urząd Skarbowy w Brodnicy ",
        "Urząd Skarbowy w Brzegu ",
        "Urząd Skarbowy w Brzesku ",
        "Urząd Skarbowy w Brzezinach ",
        "Urząd Skarbowy w Brzozowie ",
        "Urząd Skarbowy w Busku-Zdroju ",
        "Urząd Skarbowy w Bystrzycy Kłodzkiej ",
        "Urząd Skarbowy w Bytomiu ",
        "Urząd Skarbowy w Bytowie ",
        "Urząd Skarbowy w Chełmie ",
        "Urząd Skarbowy w Chełmnie ",
        "Urząd Skarbowy w Chodzieży ",
        "Urząd Skarbowy w Chojnicach ",
        "Urząd Skarbowy w Chorzowie ",
        "Urząd Skarbowy w Choszcznie ",
        "Urząd Skarbowy w Chrzanowie ",
        "Urząd Skarbowy w Ciechanowie ",
        "Urząd Skarbowy w Cieszynie ",
        "Urząd Skarbowy w Czarnkowie ",
        "Urząd Skarbowy w Czechowicach-Dziedzicach ",
        "Urząd Skarbowy w Człuchowie ",
        "Urząd Skarbowy w Dąbrowie Górniczej ",
        "Urząd Skarbowy w Dąbrowie Tarnowskiej ",
        "Urząd Skarbowy w Dębicy ",
        "Urząd Skarbowy w Drawsku Pomorskim ",
        "Urząd Skarbowy w Drezdenku ",
        "Urząd Skarbowy w Działdowie ",
        "Urząd Skarbowy w Dzierżoniowie ",
        "Urząd Skarbowy w Elblągu ",
        "Urząd Skarbowy w Ełku ",
        "Urząd Skarbowy we Włocławku ",
        "Urząd Skarbowy we Włodawie ",
        "Urząd Skarbowy we Włoszczowie ",
        "Urząd Skarbowy we Wrześni ",
        "Urząd Skarbowy we Wschowie ",
        "Urząd Skarbowy w Garwolinie ",
        "Urząd Skarbowy w Giżycku ",
        "Urząd Skarbowy w Głogowie ",
        "Urząd Skarbowy w Głownie ",
        "Urząd Skarbowy w Głubczycach ",
        "Urząd Skarbowy w Gnieźnie ",
        "Urząd Skarbowy w Goleniowie ",
        "Urząd Skarbowy w Golubiu-Dobrzyniu ",
        "Urząd Skarbowy w Gorlicach ",
        "Urząd Skarbowy w Górze ",
        "Urząd Skarbowy w Gorzowie Wielkopolskim ",
        "Urząd Skarbowy w Gostyninie ",
        "Urząd Skarbowy w Gostyniu ",
        "Urząd Skarbowy w Grajewie ",
        "Urząd Skarbowy w Grodzisku Mazowieckim ",
        "Urząd Skarbowy w Grodzisku Wielkopolskim ",
        "Urząd Skarbowy w Grójcu ",
        "Urząd Skarbowy w Grudziądzu ",
        "Urząd Skarbowy w Gryficach ",
        "Urząd Skarbowy w Gryfinie ",
        "Urząd Skarbowy w Hajnówce ",
        "Urząd Skarbowy w Hrubieszowie ",
        "Urząd Skarbowy w Iławie ",
        "Urząd Skarbowy w Inowrocławiu ",
        "Urząd Skarbowy w Janowie Lubelskim ",
        "Urząd Skarbowy w Jarocinie ",
        "Urząd Skarbowy w Jarosławiu ",
        "Urząd Skarbowy w Jaśle ",
        "Urząd Skarbowy w Jastrzębiu-Zdroju ",
        "Urząd Skarbowy w Jaworze ",
        "Urząd Skarbowy w Jaworznie ",
        "Urząd Skarbowy w Jędrzejowie ",
        "Urząd Skarbowy w Jeleniej Górze ",
        "Urząd Skarbowy w Kamieniu Pomorskim ",
        "Urząd Skarbowy w Kamiennej Górze ",
        "Urząd Skarbowy w Kartuzach ",
        "Urząd Skarbowy w Kazimierzy Wielkiej ",
        "Urząd Skarbowy w Kędzierzynie-Koźlu ",
        "Urząd Skarbowy w Kępnie ",
        "Urząd Skarbowy w Kętrzynie ",
        "Urząd Skarbowy w Kłobucku ",
        "Urząd Skarbowy w Kłodzku ",
        "Urząd Skarbowy w Kluczborku ",
        "Urząd Skarbowy w Kolbuszowej ",
        "Urząd Skarbowy w Kole ",
        "Urząd Skarbowy w Kolnie ",
        "Urząd Skarbowy w Kołobrzegu ",
        "Urząd Skarbowy w Koninie ",
        "Urząd Skarbowy w Końskich ",
        "Urząd Skarbowy w Kościanie ",
        "Urząd Skarbowy w Kościerzynie ",
        "Urząd Skarbowy w Kozienicach ",
        "Urząd Skarbowy w Krapkowicach ",
        "Urząd Skarbowy w Kraśniku ",
        "Urząd Skarbowy w Krasnymstawie ",
        "Urząd Skarbowy w Krośnie ",
        "Urząd Skarbowy w Krośnie Odrzańskim ",
        "Urząd Skarbowy w Krotoszynie ",
        "Urząd Skarbowy w Kutnie ",
        "Urząd Skarbowy w Kwidzynie ",
        "Urząd Skarbowy w Łańcucie ",
        "Urząd Skarbowy w Łasku ",
        "Urząd Skarbowy w Lęborku ",
        "Urząd Skarbowy w Łęcznej ",
        "Urząd Skarbowy w Łęczycy ",
        "Urząd Skarbowy w Legionowie ",
        "Urząd Skarbowy w Legnicy ",
        "Urząd Skarbowy w Lesku ",
        "Urząd Skarbowy w Lesznie ",
        "Urząd Skarbowy w Leżajsku ",
        "Urząd Skarbowy w Limanowej ",
        "Urząd Skarbowy w Lipnie ",
        "Urząd Skarbowy w Lipsku ",
        "Urząd Skarbowy w Łomży ",
        "Urząd Skarbowy w Łosicach ",
        "Urząd Skarbowy w Łowiczu ",
        "Urząd Skarbowy w Lubaczowie ",
        "Urząd Skarbowy w Lubaniu ",
        "Urząd Skarbowy w Lubartowie ",
        "Urząd Skarbowy w Lubinie ",
        "Urząd Skarbowy w Lublińcu ",
        "Urząd Skarbowy w Łukowie ",
        "Urząd Skarbowy w Lwówku Śląskim ",
        "Urząd Skarbowy w Makowie Mazowieckim ",
        "Urząd Skarbowy w Malborku ",
        "Urząd Skarbowy w Miechowie ",
        "Urząd Skarbowy w Międzychodzie ",
        "Urząd Skarbowy w Międzyrzeczu ",
        "Urząd Skarbowy w Mielcu ",
        "Urząd Skarbowy w Mikołowie ",
        "Urząd Skarbowy w Miliczu ",
        "Urząd Skarbowy w Mińsku Mazowieckim ",
        "Urząd Skarbowy w Mławie ",
        "Urząd Skarbowy w Mogilnie ",
        "Urząd Skarbowy w Mońkach ",
        "Urząd Skarbowy w Myślenicach ",
        "Urząd Skarbowy w Myśliborzu ",
        "Urząd Skarbowy w Mysłowicach ",
        "Urząd Skarbowy w Myszkowie ",
        "Urząd Skarbowy w Nakle nad Notecią ",
        "Urząd Skarbowy w Namysłowie ",
        "Urząd Skarbowy w Nidzicy ",
        "Urząd Skarbowy w Nisku ",
        "Urząd Skarbowy w Nowej Rudzie ",
        "Urząd Skarbowy w Nowej Soli ",
        "Urząd Skarbowy w Nowym Dworze Mazowieckim ",
        "Urząd Skarbowy w Nowym Mieście Lubawskim ",
        "Urząd Skarbowy w Nowym Sączu ",
        "Urząd Skarbowy w Nowym Targu ",
        "Urząd Skarbowy w Nowym Tomyślu ",
        "Urząd Skarbowy w Nysie ",
        "Urząd Skarbowy w Obornikach ",
        "Urząd Skarbowy w Oławie ",
        "Urząd Skarbowy w Olecku ",
        "Urząd Skarbowy w Oleśnicy ",
        "Urząd Skarbowy w Oleśnie ",
        "Urząd Skarbowy w Olkuszu ",
        "Urząd Skarbowy w Olsztynie ",
        "Urząd Skarbowy w Opatowie ",
        "Urząd Skarbowy w Opocznie ",
        "Urząd Skarbowy w Opolu Lubelskim ",
        "Urząd Skarbowy w Ostródzie ",
        "Urząd Skarbowy w Ostrołęce ",
        "Urząd Skarbowy w Ostrowcu Świętokrzyskim ",
        "Urząd Skarbowy w Ostrowie Wielkopolskim ",
        "Urząd Skarbowy w Ostrowi Mazowieckiej ",
        "Urząd Skarbowy w Ostrzeszowie ",
        "Urząd Skarbowy w Oświęcimiu ",
        "Urząd Skarbowy w Otwocku ",
        "Urząd Skarbowy w Pabianicach ",
        "Urząd Skarbowy w Pajęcznie ",
        "Urząd Skarbowy w Parczewie ",
        "Urząd Skarbowy w Piasecznie ",
        "Urząd Skarbowy w Piekarach Śląskich ",
        "Urząd Skarbowy w Pile ",
        "Urząd Skarbowy w Pińczowie ",
        "Urząd Skarbowy w Piotrkowie Trybunalskim ",
        "Urząd Skarbowy w Piszu ",
        "Urząd Skarbowy w Pleszewie ",
        "Urząd Skarbowy w Płocku ",
        "Urząd Skarbowy w Płońsku ",
        "Urząd Skarbowy w Poddębicach ",
        "Urząd Skarbowy w Polkowicach ",
        "Urząd Skarbowy w Proszowicach ",
        "Urząd Skarbowy w Prudniku ",
        "Urząd Skarbowy w Pruszczu Gdańskim ",
        "Urząd Skarbowy w Pruszkowie ",
        "Urząd Skarbowy w Przasnyszu ",
        "Urząd Skarbowy w Przemyślu ",
        "Urząd Skarbowy w Przeworsku ",
        "Urząd Skarbowy w Przysusze ",
        "Urząd Skarbowy w Pszczynie ",
        "Urząd Skarbowy w Pucku ",
        "Urząd Skarbowy w Puławach ",
        "Urząd Skarbowy w Pułtusku ",
        "Urząd Skarbowy w Pyrzycach ",
        "Urząd Skarbowy w Raciborzu ",
        "Urząd Skarbowy w Radomsku ",
        "Urząd Skarbowy w Radziejowie ",
        "Urząd Skarbowy w Radzyniu Podlaskim ",
        "Urząd Skarbowy w Rawiczu ",
        "Urząd Skarbowy w Rawie Mazowieckiej ",
        "Urząd Skarbowy Wrocław-Fabryczna ",
        "Urząd Skarbowy Wrocław-Krzyki ",
        "Urząd Skarbowy Wrocław-Psie Pole ",
        "Urząd Skarbowy Wrocław-Śródmieście ",
        "Urząd Skarbowy Wrocław-Stare Miasto ",
        "Urząd Skarbowy w Ropczycach ",
        "Urząd Skarbowy w Rudzie Śląskiej ",
        "Urząd Skarbowy w Rybniku ",
        "Urząd Skarbowy w Rykach ",
        "Urząd Skarbowy w Rypinie ",
        "Urząd Skarbowy w Sandomierzu ",
        "Urząd Skarbowy w Sanoku ",
        "Urząd Skarbowy w Sępólnie Krajeńskim ",
        "Urząd Skarbowy w Siedlcach ",
        "Urząd Skarbowy w Siemianowicach Śląskich ",
        "Urząd Skarbowy w Siemiatyczach ",
        "Urząd Skarbowy w Sieradzu ",
        "Urząd Skarbowy w Sierpcu ",
        "Urząd Skarbowy w Skarżysku-Kamiennej ",
        "Urząd Skarbowy w Skierniewicach ",
        "Urząd Skarbowy w Słubicach ",
        "Urząd Skarbowy w Słupcy ",
        "Urząd Skarbowy w Słupsku ",
        "Urząd Skarbowy w Sochaczewie ",
        "Urząd Skarbowy w Sokółce ",
        "Urząd Skarbowy w Sokołowie Podlaskim ",
        "Urząd Skarbowy w Sopocie ",
        "Urząd Skarbowy w Sosnowcu ",
        "Urząd Skarbowy w Śremie ",
        "Urząd Skarbowy w Środzie Śląskiej ",
        "Urząd Skarbowy w Środzie Wielkopolskiej ",
        "Urząd Skarbowy w Stalowej Woli ",
        "Urząd Skarbowy w Starachowicach ",
        "Urząd Skarbowy w Stargardzie ",
        "Urząd Skarbowy w Starogardzie Gdańskim ",
        "Urząd Skarbowy w Staszowie ",
        "Urząd Skarbowy w Strzelcach Opolskich ",
        "Urząd Skarbowy w Strzelinie ",
        "Urząd Skarbowy w Strzyżowie ",
        "Urząd Skarbowy w Suchej Beskidzkiej ",
        "Urząd Skarbowy w Sulęcinie ",
        "Urząd Skarbowy w Suwałkach ",
        "Urząd Skarbowy w Świdnicy ",
        "Urząd Skarbowy w Świebodzinie ",
        "Urząd Skarbowy w Świeciu ",
        "Urząd Skarbowy w Świnoujściu ",
        "Urząd Skarbowy w Szamotułach ",
        "Urząd Skarbowy w Szczecinku ",
        "Urząd Skarbowy w Szczytnie ",
        "Urząd Skarbowy w Szydłowcu ",
        "Urząd Skarbowy w Tarnobrzegu ",
        "Urząd Skarbowy w Tarnowskich Górach ",
        "Urząd Skarbowy w Tczewie ",
        "Urząd Skarbowy w Tomaszowie Lubelskim ",
        "Urząd Skarbowy w Tomaszowie Mazowieckim ",
        "Urząd Skarbowy w Trzebnicy ",
        "Urząd Skarbowy w Tucholi ",
        "Urząd Skarbowy w Turku ",
        "Urząd Skarbowy w Tychach ",
        "Urząd Skarbowy w Ustrzykach Dolnych ",
        "Urząd Skarbowy w Wąbrzeźnie ",
        "Urząd Skarbowy w Wadowicach ",
        "Urząd Skarbowy w Wągrowcu ",
        "Urząd Skarbowy w Wałbrzychu ",
        "Urząd Skarbowy w Wałczu ",
        "Urząd Skarbowy w Węgrowie ",
        "Urząd Skarbowy w Wejherowie ",
        "Urząd Skarbowy w Wieliczce ",
        "Urząd Skarbowy w Wieluniu ",
        "Urząd Skarbowy w Wieruszowie ",
        "Urząd Skarbowy w Wodzisławiu Śląskim ",
        "Urząd Skarbowy w Wołominie ",
        "Urząd Skarbowy w Wołowie ",
        "Urząd Skarbowy w Wolsztynie ",
        "Urząd Skarbowy w Wysokiem Mazowieckiem ",
        "Urząd Skarbowy w Wyszkowie ",
        "Urząd Skarbowy w Ząbkowicach Śląskich ",
        "Urząd Skarbowy w Zabrzu ",
        "Urząd Skarbowy w Żaganiu ",
        "Urząd Skarbowy w Zakopanem ",
        "Urząd Skarbowy w Zambrowie ",
        "Urząd Skarbowy w Zamościu ",
        "Urząd Skarbowy w Żarach ",
        "Urząd Skarbowy w Zawierciu ",
        "Urząd Skarbowy w Zduńskiej Woli ",
        "Urząd Skarbowy w Zgierzu ",
        "Urząd Skarbowy w Zgorzelcu ",
        "Urząd Skarbowy w Złotoryi ",
        "Urząd Skarbowy w Złotowie ",
        "Urząd Skarbowy w Żninie ",
        "Urząd Skarbowy w Żorach ",
        "Urząd Skarbowy w Żurominie ",
        "Urząd Skarbowy w Zwoleniu ",
        "Urząd Skarbowy w Żyrardowie ",
        "Urząd Skarbowy w Żywcu ",
        "Warmińsko-Mazurski Urząd Skarbowy w Olsztynie ",
        "Zachodniopomorski Urząd Skarbowy w Szczecinie "
    ],


    'working_hours' => [
        "1/1",
        "1/2",
        "1/4",
        "3/4",

    ],


    'country' => [
        'Afganistan',
        'Albania',
        'Algieria',
        'Andora',
        'Angola',
        'Anguilla',
        'Antarktyka',
        'Antigua i Barbuda',
        'Antyle Holenderskie',
        'Arabia Saudyjska',
        'Argentyna','Armenia',
        'Aruba',
        'Australia',
        'Austria',
        'Azerbejdżan',
        'Bahamy',
        'Bahrajn',
        'Bangladesz',
        'Barbados',
        'Belgia',
        'Belize','
        Benin',
        'Bermudy',
        'Bhutan','
        Białoruś',
        'Birma',
        'Boliwia',
        'Botswana',
        'Bo?nia i Hercegowina',
        'Brazylia','
        Brunei Darussalam',
        'Brytyjskie Wyspy Dziewicze',
        'Burkina Faso',
        'Burundi',
        'Bułgaria',
        'Chile',
        'Chiny',
        'Chorwacja',
        'Cypr',
        'Czad',
        'Czarnogóra',
        'Czechy',
        'Dalekie Wyspy Mniejsze Stanów Zjednoczonych',
        'Dania',
        'Demokratyczna Republika Konga',
        'Dominika',
        'Dżibuti',
        'Egipt',
        'Ekwador',
        'Erytrea',
        'Estonia',
        'Etiopia',
        'Falklandy',
        'Federalne Stany Mikronezji',
        'Fidżi',
        'Filipiny',
        'Finlandia',
        'Francja',
        'Francuskie Terytoria Południowe',
        'Gabon',
        'Gambia',
        'Georgia Południowa i Sandwich Południowy',
        'Ghana',
        'Gibraltar',
        'Grecja',
        'Grenada',
        'Grenlandia',
        'Gruzja',
        'Guam',
        'Gujana',
        'Gujana Francuska',
        'Gwadelupa',
        'Gwatemala',
        'Gwinea',
        'Gwinea Bissau',
        'Gwinea Równikowa',
        'Haiti',
        'Hiszpania',
        'Holandia',
        'Honduras',
        'Hongkong, Specjalny Region Administracyjny Chin',
        'Indie',
        'Indonezja',
        'Irak',
        'Iran',
        'Irlandia',
        'Islandia',
        'Izrael',
        'Jamajka',
        'Japonia',
        'Jemen',
        'Jordania',
        'Kajmany',
        'Kambodża',
        'Kamerun',
        'Kanada',
        'Katar',
        'Kazachstan',
        'Kenia',
        'Kirgistan',
        'Kiribati',
        'Kolumbia',
        'Komory',
        'Kongo',
        'Korea Południowa',
        'Korea Północna',
        'Kostaryka',
        'Kuba',
        'Kuwejt',
        'Laos',
        'Lesotho',
        'Liban',
        'Liberia',
        'Libia',
        'Liechtenstein',
        'Litwa',
        'Luksemburg',
        'Łotwa',
        'Macedonia',
        'Madagaskar',
        'Majotta',
        'Makau, Specjalny Region Administracyjny Chin',
        'Malawi',
        'Malediwy',
        'Malezja',
        'Mali',
        'Malta',
        'Mariany Północne',
        'Maroko',
        'Martynika',
        'Mauretania',
        'Mauritius',
        'Meksyk',
        'Monako',
        'Mongolia',
        'Montserrat',
        'Mozambik',
        'Mołdawia',
        'Namibia',
        'Nauru',
        'Nepal',
        'Niemcy',
        'Niger',
        'Nigeria',
        'Nikaragua',
        'Niue',
        'Norfolk',
        'Norwegia',
        'Nowa Kaledonia',
        'Nowa Zelandia',
        'Oman',
        'Pakistan',
        'Palau',
        'Panama',
        'Papua Nowa Gwinea',
        'Paragwaj',
        'Peru',
        'Pitcairn',
        'Polinezja Francuska',
        'Polska',
        'Portoryko',
        'Portugalia',
        'Republika Dominikańska',
        'Republika Południowej Afryki',
        'Republika Zielonego Przylądka',
        'Republika ?rodkowoafryka?ska',
        'Reunion',
        'Rosja',
        'Rumunia',
        'Rwanda',
        'Sahara Zachodnia',
        'Saint Barthélemy',
        'Saint Kitts i Nevis',
        'Saint Lucia','Saint Vincent i Grenadyny',
        'Saint-Pierre i Miquelon',
        'Salwador',
        'Samoa',
        'Samoa Amerykańskie',
        'San Marino',
        'Senegal',
        'Serbia',
        'Serbia i Czarnogóra',
        'Seszele',
        'Sierra Leone',
        'Singapur',
        'Sint Maarten',
        'Somalia',
        'Sri Lanka',
        'Stany Zjednoczone',
        'Suazi',
        'Sudan',
        'Surinam',
        'Svalbard i Jan Mayen',
        'Syria',
        'Szwajcaria',
        'Szwecja','Słowacja',
        'Słowenia',
        'Tadżykistan',
        'Tajlandia',
        'Tajwan',
        'Tanzania',
        'Terytoria Palestyńskie',
        'Terytorium Brytyjskie Oceanu Indyjskiego',
        'Timor Wschodni',
        'Togo',
        'Tokelau',
        'Tonga',
        'Trynidad i Tobago',
        'Tunezja',
        'Turcja',
        'Turkmenistan',
        'Turks i Caicos',
        'Tuvalu',
        'Uganda',
        'Ukraina',
        'Urugwaj',
        'Uzbekistan',
        'Vanuatu',
        'Wallis i Futuna',
        'Watykan',
        'Wenezuela',
        'Wielka Brytania',
        'Wietnam',
        'Wybrzeże Kości Słoniowej',
        'Wyspa Bouveta',
        'Wyspa Bożego Narodzenia',
        'Wyspa Guernsey',
        'Wyspa Jersey',
        'Wyspa Man',
        'Wyspa Świętej Heleny',
        'Wyspy Alandzkie',
        'Wyspy Cooka',
        'Wyspy Dziewicze Stanów Zjednoczonych',
        'Wyspy Heard i McDonalda',
        'Wyspy Kokosowe',
        'Wyspy Marshalla',
        'Wyspy Owcze','Wyspy Salomona',
        'Wyspy Świętego Tomasza i Księżyca',
        'Węgry',
        'Włochy',
        'Zambia',
        'Zimbabwe',
        'Zjednoczone Emiraty Arabskie',
       
    ],

    'type_of_day'=> [
        'Święto',
        'Wolne',
        'Praca'




    ],

];
